# Generated by Django 3.2 on 2023-02-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('rules', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('num_players', models.ManyToManyField(related_name='player_counts', to='board_game_time.PlayerNum')),
            ],
        ),
    ]
