# Generated by Django 3.2 on 2023-03-28 23:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('rules', models.URLField()),
                ('notes', models.TextField(blank=True)),
                ('owned_by', models.ManyToManyField(blank=True, related_name='owned', to=settings.AUTH_USER_MODEL)),
                ('wish_list', models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
